# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X51ie7URYXSCI3Wpczkgfl6UGpi1lvR3
"""

from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
import numpy as np

model = load_model("bone-fracture.keras")

path = input("Enter X-ray image path: ")

img = image.load_img(path, target_size=(256, 256), color_mode="rgb")
img = image.img_to_array(img)
img = img / 255.0
img = np.expand_dims(img, axis=0)

prediction = model.predict(img)

if prediction[0][0] > 0.5:
    print("Prediction: Fracture")
else:
    print("Prediction: No Fracture")

